import type { Metadata } from "next";
import "./globals.css";
import { ExpenseSummary } from "./components/expense-summary/expense-summary";
import { Nav } from "./components/nav/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  category,
  expense,
}: Readonly<{
  children: React.ReactNode;
  category: React.ReactNode;
  expense: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-background text-pageBackground">
        <main className="flex w-dvw h-dvh pr-4 pb-4 pt-6 overflow-x-hidden  overflow-y-auto lg:overflow-y-hidden">
          <Nav />
          <div className="flex flex-wrap w-full ml-4 md:ml-[40px] rounded-2xl bg-pageBackground text-text">
            <div className="w-full md:w-[calc(100%-250px)] lg:w-[calc(100%-350px)] px-8 py-6 md:px-20 md:py-10 lg:px-28 lg:py-20">
              {children}
              {category}
              {expense}
            </div>
            <aside className="md:flex rounded-b-2xl md:rounded-2xl bg-siderBackground h-fit md:h-full w-full md:w-[250px] lg:w-[350px] px-2 md:px-4 lg:px-14 py-8">
              <ExpenseSummary />
            </aside>
          </div>
        </main>
      </body>
    </html>
  );
}
